version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root      
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  eureka-service:    
    container_name: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile    
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8761:8761"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - app-network      
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  customer-service:    
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile    
    depends_on:
      - eureka-service    
      - mysql
      - rabbitmq
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network

  order-service:    
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile    
    depends_on:
      - eureka-service
      - mysql
      - rabbitmq
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network


  product-service:    
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile    
    depends_on:
      - eureka-service
      - mysql
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile    
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/      
    depends_on:
      - customer-service
      - order-service
      - product-service      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  rabbitmq-data: