version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root      
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - app-network      
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  eureka-service:
    image: eureka-service
    container_name: eureka-service
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8761:8761"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5      
    networks:
      - app-network

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/      
    depends_on:
      eureka-service:
        condition: service_started
      customer-service:
        condition: service_started
      order-service:
        condition: service_started
      product-service:
        condition: service_started
      consumer-service:
        condition: service_started
    networks:
      - app-network      

  customer-service:
    image: customer-service
    container_name: customer-service
    depends_on:
      eureka-service:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network

  product-service:
    image: product-service
    container_name: product-service
    depends_on:
      eureka-service:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network

  order-service:
    image: order-service
    container_name: order-service
    depends_on:
      eureka-service:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network
  
  consumer-service:    
    image: consumer-service
    container_name: consumer-service
    depends_on:
      eureka-service:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser
      SPRING_RABBITMQ_PASSWORD: mypassword
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  rabbitmq-data: